### ISSUE TITLE
Traits support

### ISSUE THREAD

**Issue by The1nk** [The1nk/RimWorld-WorkGroups#11]
Traits will be added, and I’m thinking of 3 lists for traits - must have, want to have, and can’t have. If there’s any in the must have list then every pawn must have those traits to be eligible. If any in want to have, pawns with 1+ of those will be selected first. If a pawn has any of the can’t have ones then .. they’re not eligible.

**Comment by HawnHan** [comment]
Awesome idea

**Comment by The1nk** [comment]
af3e6d7ae3670aa6b0637bbe3234ae9dbb00dbf6
