### ISSUE TITLE
[Feat] Support for more granular, individual worktypes

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [The1nk/RimWorld-WorkGroups#19]
At the moment, you lose a lot of configurability when switching from "normal" gameplay with Fluffy's WorkTabo, to "automated" gameplay with WorkGroups.

In particular, there's a lot of poorly- or annoyingly-categorized jobs, that you *really* want to assign to different people (or just generally have different rules for); with the WorkTab, you can set this up fairly easily, but it'll immediately be overwritten by WorkGroups. A couple examples:

1. You really want a WG with multiple high-Handle colonists to spread the load of Shear, Milk, Train, etc; but you *only* want your very best single Handle-er assigned to *Tame*. Ideally, I could create separate [TamerGroup] and [HandlerGroup], with their own separate rules and filters.

2. You probably want your high-social [WardenGroup] to also do VisitSickPawn, instead of wasting your [DoctorGroup]'s time. Or maybe you want a [NurseGroup] to spread the load of FeedPatient, freeing up your Doctor pawns to do other things.

**Comment by The1nk** [comment]
I actually handle this in my game, by also using [Complex Jobs](https://steamcommunity.com/sharedfiles/filedetails/?id=2069684319&searchtext=Complex+jobs)
